--- #YAML:1.0
name: Term-CallEditor
abstract: solicit data from an external editor
version: 0.50
author:
  - Jeremy Mates <jmates@sial.org>
license: artistic
distribution_type: module
requires:
  perl: 5.006
  File::Temp: 0.18
  IO::Handle: 0
build_requires:
  Test::More: 0.72
resources:
  license: http://dev.perl.org/licenses/artistic.html
  repository: http://github.com/thrig/Term-CallEditor
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Term-CallEditor
meta-spec:
  version: 1.4
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: hand
