#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Editor
version:      0.05
version_from: lib/Editor.pm
installdirs:  site
requires:
    File::Temp:                    0.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
