---
abstract: 'solicit data from an external editor'
author:
  - 'Jeremy Mates, <jmates@sial.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.72
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-CallEditor
no_index:
  directory:
    - inc
    - t
requires:
  File::Temp: 0.18
  IO::Handle: 0
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Term-CallEditor
  license: http://dev.perl.org/licenses/artistic.html
  repository: http://github.com/thrig/Term-CallEditor
version: 0.50
