#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Term-CallEditor
version:      0.10
version_from: lib/Term/CallEditor.pm
installdirs:  site
requires:
    File::Temp:                    0.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
